instructions:
  - id: TempContract
    type: deploy
    sequential: false
    rpcURL: https://polygon-mumbai.g.alchemy.com/v2/VUq8Nxd1_VYC2aA7R0ySc1kqL05cw0CF
    wssURL: wss://polygon-mumbai.g.alchemy.com/v2/VUq8Nxd1_VYC2aA7R0ySc1kqL05cw0CF
    senderKey: 17b7ef4a5238a7aabf89da4d4ccf3ec037234f7f1dae0ac780216c85767e5269
    contractPath: ./contracts/temp.sol
    contractName: Temp
    params:
      - data: "0x594f1bb1b66718D3f4C8652B931045d4fB5F8d15"
      - data: "11111111111111222222222222"
    value: 0
    gasLimit: 3000000
    childCalls:
      - id: TempContract_tempFunc1
        type: call
        sequential: true
        rpcURL: https://polygon-mumbai.g.alchemy.com/v2/VUq8Nxd1_VYC2aA7R0ySc1kqL05cw0CF
        wssURL: wss://polygon-mumbai.g.alchemy.com/v2/VUq8Nxd1_VYC2aA7R0ySc1kqL05cw0CF
        senderKey: 17b7ef4a5238a7aabf89da4d4ccf3ec037234f7f1dae0ac780216c85767e5269
        contractPath: ./contracts/temp.sol
        contractAddress: TempContract.0
        contractName: Temp
        methodName: tempFunc1
        params:
          - data: "TempContract.0"
            isInstructionKey: true
          - data: "10000"
            isInstructionKey: false
        value: 0
      - id: TempContract_tempData
        type: read
        sequential: true
        rpcURL: https://polygon-mumbai.g.alchemy.com/v2/VUq8Nxd1_VYC2aA7R0ySc1kqL05cw0CF
        senderKey: 17b7ef4a5238a7aabf89da4d4ccf3ec037234f7f1dae0ac780216c85767e5269
        contractPath: ./contracts/temp.sol
        contractName: Temp
        contractAddress: TempContract.0
        methodName: tempData
        value: 0

      - id: TempContract2
        type: deploy
        sequential: true
        rpcURL: https://polygon-mumbai.g.alchemy.com/v2/VUq8Nxd1_VYC2aA7R0ySc1kqL05cw0CF
        wssURL: wss://polygon-mumbai.g.alchemy.com/v2/VUq8Nxd1_VYC2aA7R0ySc1kqL05cw0CF
        senderKey: 17b7ef4a5238a7aabf89da4d4ccf3ec037234f7f1dae0ac780216c85767e5269
        contractPath: ./contracts/temp.sol
        contractName: Temp
        params:
          - data: "TempContract.0"
            isInstructionKey: true
          - data: "TempContract_tempData.0"
            isInstructionKey: true
        value: 0
        gasLimit: 3000000

      - id: TempContract2_tempFunc1
        type: call
        sequential: true
        rpcURL: https://polygon-mumbai.g.alchemy.com/v2/VUq8Nxd1_VYC2aA7R0ySc1kqL05cw0CF
        wssURL: wss://polygon-mumbai.g.alchemy.com/v2/VUq8Nxd1_VYC2aA7R0ySc1kqL05cw0CF
        senderKey: 17b7ef4a5238a7aabf89da4d4ccf3ec037234f7f1dae0ac780216c85767e5269
        contractPath: ./contracts/temp.sol
        contractAddress: TempContract2.0
        contractName: Temp
        methodName: tempFunc1
        params:
          - data: "TempContract.0"
            isInstructionKey: true
          - data: "10000"
            isInstructionKey: false
        value: 0

      - id: TempContract1_tempData
        type: read
        sequential: true
        rpcURL: https://polygon-mumbai.g.alchemy.com/v2/VUq8Nxd1_VYC2aA7R0ySc1kqL05cw0CF
        senderKey: 17b7ef4a5238a7aabf89da4d4ccf3ec037234f7f1dae0ac780216c85767e5269
        contractPath: ./contracts/temp.sol
        contractName: Temp
        contractAddress: TempContract2.0
        methodName: tempData
        value: 0

  - id: TempContract10
    type: deploy
    sequential: true
    rpcURL: https://polygon-mumbai.g.alchemy.com/v2/barNHxwKcvdxJuDoKlbor5qx6mhT2C_O
    wssURL: wss://polygon-mumbai.g.alchemy.com/v2/barNHxwKcvdxJuDoKlbor5qx6mhT2C_O
    senderKey: 89f220a8315a440fa258b81fd1427c926725a971288672837108386ce73ad83a
    contractPath: ./contracts/temp.sol
    contractName: Temp
    params:
      - data: "0x594f1bb1b66718D3f4C8652B931045d4fB5F8d15"
      - data: "1110100101010"
    value: 0
    gasLimit: 3000000
